//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sierrasoftworks.com/WebComicDownloader", IsNullable=false)]
public partial class Comic {
    
    private ComicDetails detailsField;
    
    private ComicXPath xPathField;
    
    private ComicAdvanced advancedField;
    
    /// <remarks/>
    public ComicDetails Details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
    
    /// <remarks/>
    public ComicXPath XPath {
        get {
            return this.xPathField;
        }
        set {
            this.xPathField = value;
        }
    }
    
    /// <remarks/>
    public ComicAdvanced Advanced {
        get {
            return this.advancedField;
        }
        set {
            this.advancedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicDetails {
    
    private ComicDetailsName nameField;
    
    private ComicDetailsAuthor authorField;
    
    private ComicDetailsAddress addressField;
    
    private ComicDetailsFirstComicAddress firstComicAddressField;
    
    private ComicDetailsLastComicAddress lastComicAddressField;
    
    /// <remarks/>
    public ComicDetailsName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public ComicDetailsAuthor Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public ComicDetailsAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public ComicDetailsFirstComicAddress FirstComicAddress {
        get {
            return this.firstComicAddressField;
        }
        set {
            this.firstComicAddressField = value;
        }
    }
    
    /// <remarks/>
    public ComicDetailsLastComicAddress LastComicAddress {
        get {
            return this.lastComicAddressField;
        }
        set {
            this.lastComicAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicDetailsName {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicDetailsAuthor {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicDetailsAddress {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicDetailsFirstComicAddress {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicDetailsLastComicAddress {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicXPath {
    
    private ComicXPathImage imageField;
    
    private ComicXPathNext nextField;
    
    private ComicXPathPrevious previousField;
    
    /// <remarks/>
    public ComicXPathImage Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    public ComicXPathNext Next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    public ComicXPathPrevious Previous {
        get {
            return this.previousField;
        }
        set {
            this.previousField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicXPathImage {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicXPathNext {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicXPathPrevious {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicAdvanced {
    
    private ComicAdvancedReferrer referrerField;
    
    private ComicAdvancedFileNaming fileNamingField;
    
    /// <remarks/>
    public ComicAdvancedReferrer Referrer {
        get {
            return this.referrerField;
        }
        set {
            this.referrerField = value;
        }
    }
    
    /// <remarks/>
    public ComicAdvancedFileNaming FileNaming {
        get {
            return this.fileNamingField;
        }
        set {
            this.fileNamingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicAdvancedReferrer {
    
    private bool useComicPathField;
    
    private bool useComicPathFieldSpecified;
    
    private string customPathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool UseComicPath {
        get {
            return this.useComicPathField;
        }
        set {
            this.useComicPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UseComicPathSpecified {
        get {
            return this.useComicPathFieldSpecified;
        }
        set {
            this.useComicPathFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CustomPath {
        get {
            return this.customPathField;
        }
        set {
            this.customPathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sierrasoftworks.com/WebComicDownloader")]
public partial class ComicAdvancedFileNaming {
    
    private string xPathField;
    
    private string patternField;
    
    public ComicAdvancedFileNaming() {
        this.xPathField = "";
        this.patternField = "%Index% - %Image%";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string XPath {
        get {
            return this.xPathField;
        }
        set {
            this.xPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("%Index% - %Image%")]
    public string Pattern {
        get {
            return this.patternField;
        }
        set {
            this.patternField = value;
        }
    }
}
